version: '3.5'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  celery-work-farm:
    image: celery-work-farm:latest
    container_name: celery-work-farm
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
